FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    AGENT_MAX_STEPS=16 \
    AGENT_MAX_WORKERS=8 \
    AGENT_TASK_TIMEOUT_SECONDS=600 \
    AGENT_PROMPT_HISTORY_STEPS=5 \
    AGENT_FULL_OBSERVATION_THRESHOLD=6000 \
    AGENT_OBSERVATION_HEAD_CHARS=1800 \
    AGENT_OBSERVATION_TAIL_CHARS=1800 \
    AGENT_STDERR_TAIL_CHARS=4000 \
    AGENT_FINAL_MARKER_CHARS=4000

WORKDIR /app

COPY pyproject.toml README.md ./
COPY src ./src
COPY main.py entrypoint.sh ./

RUN pip install --upgrade pip \
    && pip install . \
    && chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
